#!/bin/sh

# exec 1>&2
#
# if ! ./test.sh run; then
#   echo "Tests failed. Push aborted."
#   exit 1
# fi
#
# exit 0

if ! go test ./...; then
  echo "Tests failed. Push aborted."
  exit 1
fi

exit 0